version: "2"

services:
  web:
    build: .
    ports:
      - "8080"
    depends_on:
      - redis
    labels:
      - "traefik.backend=web"
      - "traefik.frontend.rule=Host:web.docker.local"

  redis:
    image: redis
    ports:
      - "6379"

networks:
  default:
    external:
      name: cerberus-net
