version: "2"

services:
  web:
    build: .
    command: ./main
    ports:
      - "8080"
    environment:
      - INTERLOCK_DATA={"hostname":"cerberus","domain":"swarm.local"}

  redis:
    image: redis
    ports:
      - "6379:6379"

networks:
  default:
    driver: overlay
