version: "2"

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    environment:
      - SERVICE_NAME=cerberus_web
      - CONSUL_IP=$CONSUL_IP
    depends_on:
      - web
    networks:
      - frontend_net

  web:
    build: .
    ports:
      - "8080"
    depends_on:
      - redis
    networks:
      - frontend_net
      - backend_net

  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - backend_net

networks:
  frontend_net:
    driver: overlay
  backend_net:
    driver: overlay
